# These are supported funding model platforms

github: abantecart
custom: ["https://www.abantecart.com/contribution"]
#custom: ["https://www.paypal.com/paypalme/abantecart", "https://www.abantecart.com/contribution"]
